### PR TITLE
Suggest array syntax while in method call

### PR DESCRIPTION
**Pull request by IanVaughan**

### CODE REVIEW

**Comment by wilsonsilva** [comment]
:+1:

**Comment by IanVaughan** [comment]
@brett-richardson / @danhawkins

**Comment by brett-richardson** [comment]
:-1:  due to over indentation

The left edge of the code and its indentation level is the quickest way to groc the underlying structure of the code. By abusing it to make arguments hang off to the right it's very difficult to match parenthesis or spot a missing `end`

**Comment by IanVaughan** [comment]
@brett-richardson Can you give an example of how you'd like this code sample styled?

**Pull request closed without merging**
