### PR TITLE
factorygirl create does not need parentheses

### PR DESCRIPTION
**Pull request by IanVaughan**

### CODE REVIEW

**Comment by wilsonsilva** [comment]
:+1:

**Comment by IanVaughan** [comment]
@brett-richardson / @danhawkins

**Comment by brett-richardson** [comment]
:+1: :+1: 
I believe _any_ single method call occurring directly in an inline block _should_ omit its parenthesis.
There is already punctuation there to visually separate the call... Why add more visual noise when you're adding no extra clarity?

**Comment by IanVaughan** [comment]
Can you give some examples here, or maybe submit a bad/ok/good block somewhere?
I think there are still cases for it personally.

**Pull request merged**
