### PR TITLE
Opt for always using double quoted strings

### PR DESCRIPTION
**Pull request by IanVaughan**
It was once a long time ago faster to use single quotes, but now they are both the same if no interpolation is required.
Staying with double means less to change if a interpolation is required later.

### CODE REVIEW

**Comment by wilsonsilva** [comment]
:-1: single quotes are easier to read.

**Comment by IanVaughan** [comment]
@brett-richardson / @danhawkins

**Comment by brett-richardson** [comment]
Agree with Wilson :-1:

**Comment by IanVaughan** [comment]
> single quotes are easier to read.

wat!

```
"This string is no"
'easier to read that this'
```

In fact, its clearer and easier to spot that `"` than it is `'`, so I find `"` strings much more intentful.

But fair enough, unless @danhawkins overrides the tie, we'll stick to `'`.

**Comment by brett-richardson** [comment]
I tend to use the 2 types to convey additional meaning.

`"` is a string that is intended for human comprehension.
Error logs, Rspec descriptions (generally the things that require interpolation)

`'` is a string for machine consumption.
Array keys, enums, types etc.

**Comment by wilsonsilva** [comment]
I use `"` when the string has interpolation or escaping sequences, and `'` otherwise.

**Comment by danhawkins** [comment]
I am a ' kind of guy also

**Comment by danhawkins** [comment]
@brett-richardson reasoning sounds ok , usually I am just doubles for interpolation

**Pull request closed without merging**
