### PR TITLE
Suggest indentation that matches previous rule

### PR DESCRIPTION
**Pull request by IanVaughan**
https://github.com/QuiqUpLTD/ruby-style-guide/blob/master/README.md#indent-conditional-assignment

### CODE REVIEW

**Comment by wilsonsilva** [comment]
:+1:

**Comment by IanVaughan** [comment]
@brett-richardson / @danhawkins

**Comment by brett-richardson** [comment]
:100: :-1:

**Comment by brett-richardson** [comment]
The left edge of the code and its indentation level is the quickest way to groc the underlying structure of the code. By abusing it to make arguments hang off to the right it's very difficult to match parenthesis or spot a missing end

**Comment by brett-richardson** [comment]
Not to mention a PITA to type!

**Comment by IanVaughan** [comment]
> Not to mention a PITA to type!

Auto-indent FTW!

**Comment by IanVaughan** [comment]
> The left edge of the code and its indentation level is the quickest way to groc the underlying structure of the code

Exactly!

Thus, I so ever so clearly see an assignment based on a conditionally here!

Can you provide some alternative suggestions?

**Comment by danhawkins** [comment]
I actually prefer the previous version, especially if the conditional block gets bigger, then it becomes hard to see where you are indented to

**Pull request closed without merging**
