### PR TITLE
 Limit lines to 120

### PR DESCRIPTION
**Pull request by IanVaughan**

### CODE REVIEW

**Comment by wilsonsilva** [comment]
:+1:

**Comment by IanVaughan** [comment]
@brett-richardson / @danhawkins

**Comment by brett-richardson** [comment]
:( this :+1:  comes only under duress.

**Comment by IanVaughan** [comment]
> :( this :+1: comes only under duress.

lol, yeah me too, I'll come _down_ to 120! :trollface:

**Pull request merged**
